import { lazy, Suspense, useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, Pause, Play, X, Menu, SlidersHorizontal, Terminal, Lightbulb, Layers, Plus } from 'lucide-react';
import { PORTFOLIO_DATA as data, type Project } from './data/portfolioData';
import { ProjectDetails, About, Experience, Recognition, Contact } from './PortfolioContent';
import { CyberTerminal } from './components/ui/CyberTerminal';
const WorldScene=lazy(()=>import('./components/3d/WorldScene'));
const stops=[['hero','Welcome'],['projects','Work'],['experience','Experience'],['about','About'],['contact','Contact']];
function External({href,children}:{href:string;children:ReactNode}){return <a href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={16}/></a>;}
function Chapter({id,index,children}:{id:string;index:number;children:ReactNode}){return <section id={id} data-stop={index} className={`journey-chapter chapter-${index}`}><div className="chapter-stage"><div className="chapter-copy">{children}</div></div></section>;}
function Dossier({kind,onClose}:{kind:string|null;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(!kind)return;const el=ref.current!;const focus=document.activeElement as HTMLElement;const previous=document.body.style.overflow;document.body.style.overflow='hidden';el.showModal();return()=>{el.close();document.body.style.overflow=previous;focus?.focus();};},[kind]);
 return <dialog ref={ref} className="dossier" aria-label={kind==='about'?'About Samyak and skills':kind==='experience'?'Full experience':kind==='awards'?'Recognition':kind==='services'?'Working together':'Contact Samyak'} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><button className="dossier-close" onClick={onClose} aria-label="Close details"><X size={21}/></button>{kind==='about'?<About/>:kind==='experience'?<Experience/>:kind==='awards'?<Recognition/>:kind==='contact'?<Contact/>:kind==='services'?<section className="section"><span className="eyebrow">Working together</span><h2>From idea<br/>to first version.</h2><div className="service-list">{data.freelanceServices.map(s=><details key={s.title}><summary><h3>{s.title}</h3><Plus size={18}/></summary><div><p>{s.description}</p><div className="stack-list">{s.tags.map(t=><span key={t}>{t}</span>)}</div></div></details>)}</div></section>:null}</dialog>;
}
export function App(){
 const [project,setProject]=useState(0),[details,setDetails]=useState<Project|null>(null),[dossier,setDossier]=useState<string|null>(null);
 const [paused,setPaused]=useState(false),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[quality,setQuality]=useState(true);
 const [lights,setLights]=useState(true),[exploded,setExploded]=useState(false),[ready,setReady]=useState(false),[active,setActive]=useState(0),[menu,setMenu]=useState(false),[settings,setSettings]=useState(false),[terminal,setTerminal]=useState(false);
 const [role,setRole]=useState(0); const settingsRef=useRef<HTMLDivElement>(null);const settingsButton=useRef<HTMLButtonElement>(null);const menuButton=useRef<HTMLButtonElement>(null);
 const motionPaused=paused||reduced,selected=data.projects[project];
 const markReady=useCallback(()=>setReady(true),[]);const toggleDesk=useCallback(()=>setLights(v=>!v),[]);const openProject=useCallback(()=>setDetails(data.projects[project]),[project]);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{document.documentElement.dataset.motion=motionPaused?'paused':'on';},[motionPaused]);
 useEffect(()=>{const read=()=>{let next=0;document.querySelectorAll<HTMLElement>('[data-stop]').forEach((el,i)=>{if(el.getBoundingClientRect().top<innerHeight*.25)next=i;});setActive(next);};window.addEventListener('scroll',read,{passive:true});read();return()=>window.removeEventListener('scroll',read);},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(settings)settingsButton.current?.focus();if(menu)menuButton.current?.focus();setSettings(false);setMenu(false);}if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable]'))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setTerminal(v=>!v);}};const outside=(e:PointerEvent)=>{if(!settingsRef.current?.contains(e.target as Node))setSettings(false);};window.addEventListener('keydown',key);document.addEventListener('pointerdown',outside);return()=>{window.removeEventListener('keydown',key);document.removeEventListener('pointerdown',outside);};},[settings,menu]);
 return <div className="journey-shell"><a className="skip-link" href="#projects">Skip to work</a><Suspense fallback={<div className="world-placeholder"/>}><WorldScene paused={motionPaused} quality={quality} project={selected.hologramType} projectIndex={project} lights={lights} exploded={exploded} onProject={openProject} onDesk={toggleDesk} onReady={markReady}/></Suspense><div className="world-shade" aria-hidden="true"/>
 <header className="journey-header"><a href="#hero" className="journey-brand" aria-label="Samyak Jain home">samyak<span>.</span></a><nav className={menu?'journey-nav open':'journey-nav'} aria-label="Main navigation">{stops.slice(1).map(([id,label],i)=><a key={id} href={`#${id}`} aria-current={active===i+1?'location':undefined} onClick={()=>setMenu(false)}>{label}</a>)}<External href={data.personal.socials.blog}>Writing</External></nav><div className="journey-tools"><div ref={settingsRef} className="settings-wrap"><button ref={settingsButton} className="icon-button" aria-label="Experience settings" aria-expanded={settings} onClick={()=>setSettings(v=>!v)}><SlidersHorizontal size={18}/></button>{settings&&<div className="settings-panel"><span className="eyebrow">At your own pace</span><button disabled={reduced} onClick={()=>setPaused(v=>!v)}>{motionPaused?'Resume motion':'Pause motion'}{reduced&&' · system preference'}</button><button aria-pressed={!quality} onClick={()=>setQuality(v=>!v)}>Lightweight rendering <span>{quality?'Off':'On'}</span></button><button onClick={()=>{setTerminal(true);setSettings(false);}}><Terminal size={16}/>Open terminal <kbd>⌘K</kbd></button></div>}</div><button ref={menuButton} className="journey-menu icon-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>{menu?<X size={20}/>:<Menu size={20}/>}</button><a className="journey-talk" href="#contact">Let’s talk <ArrowUpRight size={16}/></a></div></header>
 <main className="journey-main">
 <Chapter id="hero" index={0}><span className="chapter-eyebrow"><span className="status-dot"/>PUNE, INDIA · SOFTWARE ENGINEER</span><h1>Samyak<br/>Jain<span>.</span></h1><p className="intro-line">Systems by day.<br/><span>Possibilities after hours.</span></p><p className="chapter-description">Software Engineer at UBS.<br/>Building AI products. Studying finance at XLRI.</p><a className="journey-link" href="#projects">Come on in <ArrowDown size={19}/></a><button className="object-control" aria-pressed={lights} onClick={toggleDesk}><Lightbulb size={14}/>{lights?'Turn the desk light off':'Turn the desk light on'}</button></Chapter>
 <Chapter id="projects" index={1}><span className="chapter-eyebrow">01 / THINGS I’VE BUILT</span><div className="project-chapter-heading"><h2 key={selected.id}>{selected.title}<span>.</span></h2></div><p className="project-category">{selected.category}</p><p className="chapter-description project-story">{selected.description}</p><button className="journey-link" onClick={openProject}>Inside the project <ArrowUpRight size={20}/></button><div className="journey-project-switcher"><button aria-label="Previous project" onClick={()=>setProject(p=>(p+data.projects.length-1)%data.projects.length)}><ArrowLeft size={20}/></button><span><b>{String(project+1).padStart(2,'0')}</b> / {String(data.projects.length).padStart(2,'0')}</span><button aria-label="Next project" onClick={()=>setProject(p=>(p+1)%data.projects.length)}><ArrowRight size={20}/></button><details className="project-picker"><summary>All work <Plus size={14}/></summary><div>{data.projects.map((p,i)=><button key={p.id} aria-pressed={project===i} onClick={e=>{setProject(i);e.currentTarget.closest('details')?.removeAttribute('open');}}><span>0{i+1}</span>{p.title}<ArrowUpRight size={14}/></button>)}</div></details></div><p className="object-hint">Select the installation to take a closer look.</p></Chapter>
 <Chapter id="experience" index={2}><span className="chapter-eyebrow">02 / UNDER THE SURFACE</span><h2>Built for the<br/>real world<span>.</span></h2><div className="career-tabs" aria-label="Select experience">{data.experience.map((e,i)=><button key={i} aria-pressed={role===i} onClick={()=>{setRole(i);setExploded(true);}}>{e.company}{i===1?' · Intern':''}</button>)}</div><p className="chapter-role">{data.experience[role].role}<small>{data.experience[role].period}</small></p><p className="chapter-description">{data.experience[role].summary}</p><button className="journey-link" onClick={()=>setDossier('experience')}>The full experience <ArrowUpRight size={19}/></button><button className="object-control" aria-pressed={exploded} onClick={()=>setExploded(v=>!v)}><Layers size={15}/>{exploded?'Bring the layers together':'Look between the layers'}</button></Chapter>
 <Chapter id="about" index={3}><span className="chapter-eyebrow">03 / STILL FIGURING THINGS OUT</span><h2>Engineer.<br/>Builder.<br/><span>Always curious.</span></h2><p className="chapter-description">I like the space where a difficult problem becomes something people can actually use. These days, that’s cloud systems, AI tools, and the occasional idea that keeps me up late.</p><div className="chapter-actions"><button className="journey-link" onClick={()=>setDossier('about')}>A little about me <ArrowUpRight size={19}/></button><button className="subtle-link" onClick={()=>setDossier('awards')}>A few milestones <Plus size={15}/></button></div><a className="award-note" href={data.personal.socials.awsArticle} target="_blank" rel="noreferrer"><span>↗</span><div>Amazon AIdeaS 2026<small>Innovation Category Winner · RetainIQ</small></div></a></Chapter>
 <Chapter id="contact" index={4}><span className="chapter-eyebrow">04 / THE NEXT CHAPTER</span><h2>What could<br/>we build<span>?</span></h2><p className="chapter-description">Have an interesting problem, a half-formed idea,<br className="desktop-break"/> or just a good hello? I’d love to hear it.</p><button className="journey-link" onClick={()=>setDossier('contact')}>Let’s start a conversation <ArrowUpRight size={20}/></button><a className="contact-direct" href={`mailto:${data.personal.email}`}>{data.personal.email}</a><button className="subtle-link" onClick={()=>setDossier('services')}>Ways we can work together <Plus size={15}/></button><div className="journey-socials"><External href={data.personal.socials.github}>GitHub</External><External href={data.personal.socials.linkedin}>LinkedIn</External><External href={data.personal.socials.twitter}>X</External><External href={data.personal.socials.sponsor}>Sponsor</External></div></Chapter>
 </main><footer className="journey-footer"><span>© {new Date().getFullYear()} Samyak Jain</span><a href="/overview.html">Project overview</a><External href={data.personal.socials.blog}>Blog</External><External href={data.personal.socials.portfolio}>samyak.space</External><a href="#hero">Back to the beginning ↑</a></footer>
 <div className="journey-status"><button disabled={reduced} onClick={()=>setPaused(v=>!v)} aria-label={reduced?'Reduced motion enabled':paused?'Resume motion':'Pause motion'}>{motionPaused?<Play size={12}/>:<Pause size={12}/>}<span>{motionPaused?'MOTION PAUSED':'TAKE YOUR TIME'}</span></button><span className="studio-note">{ready?'THE DOOR IS ALWAYS OPEN':'OPENING THE STUDIO…'}</span><nav aria-label="Journey chapters">{stops.map(([id,label],i)=><a key={id} href={`#${id}`} aria-label={`${label} chapter`} aria-current={active===i?'step':undefined}><span>0{i+1}</span></a>)}</nav></div>
 <ProjectDetails project={details} onClose={()=>setDetails(null)}/><Dossier kind={dossier} onClose={()=>setDossier(null)}/><CyberTerminal isOpen={terminal} onClose={()=>setTerminal(false)} onThemeChange={()=>{}}/>
 </div>;
}

export default App;
